name: Pulumi
on:
  push:
  pull_request:
    branches:
      - main
    types:
      - closed
      - synched
      - opened
    
env:
  PLAN_NAME: pr-${{ github.event.repository }}-${{ github.event.number }}.json
  PLAN_FILE: .pulumi/stacks/${{ github.event.repository.name }}/pr-${{ github.event.repository }}-${{ github.event.number }}.json
  AZURE_STORAGE_KEY: thaumazodev
  AZURE_STORAGE_ACCOUNT: ${{ vars.PULUMI_AZURE_BLOB_STORAGE_ACCOUNT }}
  

permissions:
      id-token: write
      contents: write
      pull-requests: write
    
jobs:
  Pulumi:
    environment: development
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'

      - name: 'Install'
        run: |
           pip install -r requirements.txt ; python -m unittest discover -p test_app.py

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Check Storage"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob list -c iac --prefix .pulumi/stacks/${{ github.event.repository.name }}


      - uses: pulumi/actions@v5
        name: "Preview PR"
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'opened' || github.event.action == 'synched' )
        with:
          command: preview
          comment-on-pr: true
          plan: ${{ env.PLAN_NAME }}
          stack-name: ${{ github.event.repository.name }}

      - name: Plan to Azure
        uses: azure/CLI@v1
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'opened' || github.event.action == 'synched' )
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload -f ${{ env.PLAN_NAME }} --overwrite true -c ${{ vars.PULUMI_AZURE_BLOB_STORAGE_CONTAINER }} -n ${{ env.PLAN_FILE }}

      - name: Plan from Azure
        uses: azure/CLI@v1
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'approved' )
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload -f ${{ env.PLAN_NAME }} -c ${{ vars.PULUMI_AZURE_BLOB_STORAGE_CONTAINER }} -n ${{ env.PLAN_FILE }}

      - uses: pulumi/actions@v5
        name: "Update Infrastructure"
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'approved' )
        with:
          command: up
          plan: ${{ env.PLAN_NAME }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'approved' )
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          method: squash # merge rebase
          repo: ${{ github.repository }}
