name: Pulumi
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
  pull_request_review:
      types: [ submitted ]
    
env:
  PLAN_NAME: pr-${{ github.event.repository }}-${{ github.event.number }}.json
  PLAN_FILE: .pulumi/stacks/${{ github.event.repository.name }}/pr-${{ github.event.repository }}-${{ github.event.number }}.json
  AZURE_STORAGE_ARGS: --only-show-errors -c ${{ vars.PULUMI_STORAGE_BLOB_CONTAINER }} --account-name ${{ vars.PULUMI_STORAGE_BLOB_ACCOUNT }}
  PULUMI_CONFIG_PASSPHRASE: ""
  PULUMI_CLOUD_URL: azblob://${{ vars.PULUMI_STORAGE_BLOB_CONTAINER }}?storage_account=${{ vars.PULUMI_STORAGE_BLOB_ACCOUNT }}
  AZURE_STORAGE_ACCOUNT: ${{ secrets.PULUMI_STORAGE_BLOB_ACCOUNT }}
  AZURE_STORAGE_KEY: ${{ secrets.PULIMI_STORAGE_BLOB_CONTAINER }}
  AZURE_KEYVAULT_AUTH_VIA_CLI: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


permissions:
      id-token: write
      contents: write
      pull-requests: write
    
jobs:
  Pulumi:
    environment: development
    name: Preview
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v4

      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: "Check Storage"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob list ${{ env.AZURE_STORAGE_ARGS }} --prefix .pulumi/stacks/${{ github.event.repository.name }}

      - name: 'Install'
        run: |
           pip install -r requirements.txt ; python -m unittest discover -p test_app.py

      - uses: pulumi/actions@v5
        name: "Preview PR"
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'opened' || github.event.action == 'synchronize' )
        with:
          command: preview
          comment-on-pr: true
          plan: ${{ env.PLAN_NAME }}
          cloud-url: ${{ env.PULUMI_CLOUD_URL }}
          stack-name: ${{ github.event.repository.name }}

      - name: Plan to Azure
        uses: azure/CLI@v1
        if: |
          github.event_name == 'pull_request' &&
          ( github.event.action == 'opened' || github.event.action == 'synchronize' )
        with:
          azcliversion: 2.30.0
          cloud-url: ${{ env.PULUMI_CLOUD_URL }}
          inlineScript: |
            az storage blob upload ${{ env.AZURE_STORAGE_ARGS }} -f ${{ env.PLAN_NAME }} --overwrite true -n ${{ env.PLAN_FILE }}

      - name: Plan from Azure
        uses: azure/CLI@v1
        if: |
          github.event.review.state == 'approved'
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload ${{ env.AZURE_STORAGE_ARGS }} -f ${{ env.PLAN_NAME }} -n ${{ env.PLAN_FILE }}

      - uses: pulumi/actions@v5
        name: "Update Infrastructure"
        if: |
          github.event.review.state == 'approved'
        with:
          command: up
          plan: ${{ env.PLAN_NAME }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        if: |
          github.event.review.state == 'approved'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          method: squash # merge rebase
          repo: ${{ github.repository }}
